version: '3'
services:
   nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    networks:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/ghost/ghost.conf:/etc/nginx/conf.d/ghost.conf:z
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/ghost/html:/var/lib/html:ro

   ghost:
    image: ghost:latest
    restart: always
    container_name: ghost
    networks:
      - ghost
    volumes:
      - /opt/ghost/content:/var/lib/ghost/content:z

networks:
  ghost:
